### ISSUE TITLE
[ON-BOARDING] A new contributor has arrived -  @username

### ISSUE THREAD

**Issue by cynthialunamaciel** [JusticeInternational/project-config#11]
We're looking for volunteers all the time, and this is the right place to get started. We'd like you to open an issue to help you get connected and help us with contributions to the projects. Please start with this check list:

- [ ] Reach out to us via [email](Carlos@alumni.stanford.edu) and let us know who you are and so we can send you more info.
- [ ] Get WhatsApp installed and setup so we can eventually connect on WhatsApp
- [ ] Learn more by reading [our docs](https://github.com/JusticeInternational/project-config/blob/master/docs/README.md)

**Comment by sfc-gh-eraigosa** [comment]
Hi @cynthialunamaciel , You should have a new invite in your email for https://github.com/orgs/JusticeInternational

I'll close this issue now, but please feel free to re-open it if the login access doesn't work 🙇🏽  Thank You!
