### ISSUE TITLE
[ON-BOARDING] A new contributor has arrived -  initial users

### ISSUE THREAD

**Issue by sfc-gh-eraigosa** [JusticeInternational/project-config#2]
We're looking for volunteers all the time, and this is the right place to get started. We'd like you to open an issue to help you get connected and help us with contributions to the projects. Please start with this check list:

- [x] Provide an email address where we can contact you so we can send more info.
- [x] Get WhatsApp installed and setup so we can eventually connect on WhatsApp
- [x] Learn more by reading [our docs](https://github.com/JusticeInternational/project-config/blob/master/docs/README.md)

I'll be onboarding these folks once we have some additional seats:

- abrito21
- Osguido

[have some more to come next week]

**Comment by Carlosgsuarez** [comment]
Email: Carlos@alumni.stanford.edu

**Comment by sfc-gh-eraigosa** [comment]
Carlos, is it ok if i change the template so folks can contact you when we have someone new?

**Comment by Carlosgsuarez** [comment]
yes, no problem at all.

**Comment by sfc-gh-eraigosa** [comment]
I'm completing this as the issue template is up to date now
