### ISSUE TITLE
Manually setting up our K8's environment

### ISSUE THREAD

**Issue by sfc-gh-eraigosa** [JusticeInternational/project-config#27]
## **Is your feature request related to a problem? Please describe.**
RedSol is working on our first deployment of our backend API services for our mobile app. For this we'd like to investigate deploying a minimal deployment of AKS. The Kubernetes env should use no more than 3 nodes, and be deployed on the smallest servers available. This is to maintain our low monthly available budget.

## **Describe the solution you'd like**
The work will be complete when the following things are possible.
	1. We are able to deploy our working [API service](https://github.com/JusticeInternational/Human-Connection/tree/stable/backend) along with [neo4j database](https://github.com/JusticeInternational/Human-Connection/tree/stable/neo4j).
	2. A https based URL is available for the API services, the neo4j interface should only be accessible with a proxy connection with kube.
	3. Persistent storage is available for the neo4j application and it is being backed up.
	4. Our team can access the kubernetes instance and authorization is provided with AD
	5. The AKS instance is being managed within a resource group
All deployment and configuration steps have been documented in the [project-config](https://github.com/JusticeInternational/project-config) repo.

## **Describe the solution you'd like**
TODO for Dev team implementing the work.

## **Describe alternatives you've considered**
TODO for Dev team implementing the work.

## **Additional context**
Note, please contact @wenlock or @Carlosgsuarez to get started so we can grant access and provide additional admin access to perform the work. We want to eventually take this work done and automate it so it's key that the documents provide details needed and step by step instructions used in the UI or cli's that allow us to accomplish the automation. We will be using this first environment for our app prototype on Android.

**Comment by Carlosgsuarez** [comment]
Gracias Edward, ya estamos trabajando en ello, cualquier comentario
adicional estaremos pendiente. Feliz inicio de semana :)

*Cristina Paz*
===============

Carlos

=======================

*Carlos G. Suarez - Entrepreneur*

Ph: +1 (650) 318-1852 (Cel/W/app)

Fax: +1 (888) 388-8213

*FB/LK/TW/SK*: CarlosGSuarez

If it is not social...

it is not entrepreneurship!

**Comment by sfc-gh-eraigosa** [comment]
> 4. Our team can access the kubernetes instance and authorization is provided with AD
> 5. The AKS instance is being managed within a resource group

With the exception of an error we get during ACR setup, this is all [but done](https://github.com/JusticeInternational/project-config/blob/stable/docs/references/kube_notes/bootstrap.md). We have a kube cluster where we are able to deploy to.

This one is up next:

> 3. Persistent storage is available for the neo4j application and it is being backed up.

**Comment by sfc-gh-eraigosa** [comment]
We followed [these instructions for the setup](https://docs.microsoft.com/en-us/azure/aks/azure-disks-dynamic-pv#back-up-a-persistent-volume), however I've opened up another issue for managing the backups, which will be needed in production:

https://github.com/JusticeInternational/project-config/issues/30

**Comment by sfc-gh-eraigosa** [comment]
This is the error we're needing to solve

```
  Normal   Pulling                 1s    kubelet                  Pulling image "redsolacr.azurecr.io/humanconnection/nitro-backend:latest"
  Warning  Failed                  1s    kubelet                  Failed to pull image "redsolacr.azurecr.io/humanconnection/nitro-backend:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://redsolacr.azurecr.io/v2/humanconnection/nitro-backend/manifests/latest: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.
  Warning  Failed                  1s    kubelet                  Error: ErrImagePull
```

And it was due to failure with [this step](https://github.com/JusticeInternational/project-config/blob/stable/docs/references/kube_notes/bootstrap.md#attach-aks-cluster-to-acr-by-name-acrname) which would be causing this problem.

```
❯ az aks update -g $RESOURCE_GROUP -n $CLUSTER_NAME \
            --attach-acr $ACR_NAME \
            --subscription $SUBSCRIPTION_ID
Waiting for AAD role to propagate[################################    ]  90.0000%Could not create a role assignment for ACR. Are you an Owner on this subscription?
```

**Comment by sfc-gh-eraigosa** [comment]
With [this workaround](https://github.com/JusticeInternational/project-config/pull/29/files#diff-a6efd6344940d2312949603aa000dace9287e399dc77dc5c932c36d16a2d3256R229-R236) set setup credentials with tokens.

We now have a deployed app but networking needs to be worked out to connect the backend with neo4j.

**Comment by sfc-gh-eraigosa** [comment]
We have this task left:

> 2. A https based URL is available for the API services, the neo4j interface should only be accessible with a proxy connection with kube.

**Comment by sfc-gh-eraigosa** [comment]
Here is another Prod item that we'll need to take care of; https://github.com/JusticeInternational/project-config/issues/31

**Comment by sfc-gh-eraigosa** [comment]
Ok, this issue is solved now and we have an API service here http://redsol.eastus.cloudapp.azure.com/

It's good for development so we'll need to do some more testing to make sure it's working but they'll be more task to improve this for production. Those would be things like;

some test for the endpoints
backups
security, secrets in AKV
end point protection (ssl, creds ??)
ci/cd
There might be more as we progress but that's a good setup we have now. Currently this will cost 50-60 /month, so we can probably have a second env for production once we get there.

**Comment by sfc-gh-eraigosa** [comment]
Here is some updates we made for testing the endpoints and docs; https://github.com/JusticeInternational/project-config/pull/35

Here is how we can test the endpoint: https://github.com/JusticeInternational/project-config/tree/stable/config#test-the-api

I'm going to close this one out as complete.
